### ISSUE TITLE
Exception when trying to get Trade Confirmation Flex Query

### ISSUE THREAD

**Issue by zdomokos** [gabbersepp/ib-flex-reader#29]
Trying to get "Trade Confirmation Flex Query", I get this exception at Reader.cs : 187

System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: <FlexQueryResponse xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderXmlFlexStatementResponse.Read6_FlexStatementResponse()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at IbFlexReader.Xml.Deserializer.Deserialize[TXml,TOut](Stream content, List`1& errorObjects)
   at IbFlexReader.Reader.TryGetFlexStatementResponse(Stream stream, FlexStatementResponse& response)

This is the response format coming back from IB:
```
<FlexQueryResponse queryName="Today" type="TCF">
    <FlexStatements count="1">
        <FlexStatement accountId="xyz" fromDate="20200603" toDate="20200603" period="Today" whenGenerated="20200603;220858">
            <TradeConfirms>
			<!-- I cut it out --> 
            </TradeConfirms>
        </FlexStatement>
    </FlexStatements>
</FlexQueryResponse>
```

**Comment by zdomokos** [comment]
Adding Biehler.EnumParser nuget it works.
